<!DOCTYPE html>
<html>
<head>
    <title>Table</title>
</head>
<body>
    <table>
        <tr>
            <td>Vezeteknev</td>
            <td>keresztnev</td>
        </tr>
        <tr>
            <td>Kocsis</td>
            <td>Géza</td>
            <td>Ferenc</td>
        </tr>
        <tr>
            <td>Horváth</td>
            <td>Mária</td>
            <td>Julia</td>
        </tr>
        <tr>
            <td>Balogh</td>
            <td>Ferenc</td>
        </tr>
        <tr>
            <td>Horváth</td>
            <td>Gábor</td>
            <td>Attila</td>
        </tr>
    </table>
</body>
</html>